### ISSUE TITLE
Migration Guide

### ISSUE THREAD

**Issue by nietsmmar** [kishan-dhankecha/carousel_slider_plus#1]
Thank you so much for this fork!

I have some trouble migration from the old package.

I couldn't find information about this in the changelog:

I used `controller.onReady` and `controller.nextPage()` and `controller.previousPage()` before but these methods aren't existing anymore.

How would I migrate this? Is there a Migration-Guide somewhere?

Thanks a lot!

**Comment by nietsmmar** [comment]
Ohhh I think I created the wrong CarouselController....

**Comment by kishan-dhankecha** [comment]
There should not be an issue like this as all those methods are still untouched by source code.

**Comment by nietsmmar** [comment]
Yes... Because my old code created a `CarouselController()` and this code still worked because of the new controller from flutter I didn't realize it. my bad.
