### ISSUE TITLE
CarouselOptions initialPage value is not updated after a setState

### ISSUE THREAD

**Issue by davidequadrelli-b** [kishan-dhankecha/carousel_slider_plus#2]
I noticed this bug with the latest version of the library. When a setState requires a redraw of the carousel, even if the `initialPage` value is updated accordingly to not change the current shown item, the carousel continue to use the first `initialPage` value passed during the creation of the component.

The following code is the example <i>BasicDemo</i> code with some changes to reproduce the problem.
```dart
class BasicDemo extends StatefulWidget {
  const BasicDemo({super.key});

  @override
  State<BasicDemo> createState() => _BasicDemoState();
}

class _BasicDemoState extends State<BasicDemo> {
  int actualPosition = 0;
  bool disableScroll = false;
  Color backgroundColor = Colors.green;

  @override
  Widget build(BuildContext context) {
    debugPrint("Actual position: $actualPosition");
    return Scaffold(
      appBar: AppBar(title: const Text('Basic demo')),
      body: CarouselSlider(
        disableGesture: disableScroll,
        options: CarouselOptions(
          initialPage: actualPosition,
          pageSnapping: true,
          onPageChanged: (index, reason) {
            actualPosition = index;
          },
        ),
        items: List.generate(5, (i) => i + 1).map((item) {
          return InkWell(
            onTap: () {
              setState(() {
                disableScroll = true;
                backgroundColor = Colors.red;
              });
              Timer(const Duration(seconds: 1), () {
                setState(() {
                  disableScroll = false;
                  backgroundColor = Colors.green;
                });
              });
            },
            child: Container(
              color: backgroundColor,
              child: Center(child: Text(item.toString())),
            ),
          );
        }).toList(),
      ),
    );
  }
}
```

If you scroll to the third item and then tap on it, the carousel will render the first item and not the third.
If you try to set `initialPosition = 1`, when you tap on an item of the carousel, the carousel will render the second item, so it always use the first value of initialPosition.

I don't know if this information can be useful, but with the original `carousel_slider` library this problem is not present.
I also attach a simple video of the issue

https://github.com/user-attachments/assets/f238c96b-4cec-4b7a-ba6c-4a3d8a17aaa7

**Comment by ifuterman** [comment]
I think, to fix this you need only add the key: ValueKey(actualPosition) to the CarouselSlider

**Comment by kishan-dhankecha** [comment]
Closing this as the last comment provides the solution for the issue.
