### ISSUE TITLE
dont't work with Stylus/Pencil

### ISSUE THREAD

**Issue by BOB4uK2023** [kishan-dhankecha/carousel_slider_plus#3]
Hi, I'm using this package, it's very nice!
But I cant scoll carusel with stylus/Pencil
I have device Samsung Galaxy S23 Ultra with Pencil

may be you have solution?

**Comment by kishan-dhankecha** [comment]
Thanks for the report!

Let me see if I can reproduce it on my `Tab S7 FE`.
