### ISSUE TITLE
space between items is more when carousel is reversed 

### ISSUE THREAD

**Issue by NeedNot** [kishan-dhankecha/carousel_slider_plus#7]
there is a significant space between items when the carousel is reversed

i posted an issue on the original carousel_slider but it's abandoned

**Comment by kishan-dhankecha** [comment]
Can you provide reproducible code so I can easily check this issue.

**Comment by NeedNot** [comment]
> Can you provide reproducible code so I can easily check this issue.

i went and changed the options of the "Complicated image slider" demo example

```
        options: CarouselOptions(
          // autoPlay: true,
          enableInfiniteScroll: false,
          reverse: false,
          viewportFraction: .92,
          enlargeCenterPage: true,
          enlargeFactor: 0.25,
          aspectRatio: 3 / 4,
          enlargeStrategy: CenterPageEnlargeStrategy.zoom,
        ),
```

simply reversing on it's own didn't cause it. reversing in combination with these settings did though


edit:
ok never mind you dont need to change the options at all, just add reverse and set the enlarge strategy to zoom, others untested

**Comment by NeedNot** [comment]
perhaps look at where the code scales with the enlarge strategy and see why it's different when reversed. has to be simple

**Comment by kishan-dhankecha** [comment]
Hello @NeedNot,

I have resolved the issue and will commit the changes shortly.

I appreciate you bringing this matter to my attention.
