### ISSUE TITLE
Stacked Images

### ISSUE THREAD

**Issue by cabonitavince** [kishan-dhankecha/carousel_slider_plus#8]
Is there any way to stack the list of images like this?

![viber_image_2024-10-12_20-50-47-118](https://github.com/user-attachments/assets/c0f3a347-996e-4ed4-9b37-be45b5a953a6)

**Comment by kishan-dhankecha** [comment]
No, we do not have this layout option on this one. Maybe you should look for another solution.

**Comment by kishan-dhankecha** [comment]
For any further questions please create a new question in the [discussion section](https://github.com/kishan-dhankecha/carousel_slider_plus/discussions/new?category=q-a).
